apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  creationTimestamp: null
  name: {{ .Values.cluster }}-openldap
  annotations:
    argocd.argoproj.io/sync-wave: "355"
    helm.sh/hook-weight: "355"
  namespace: {{ .Values.cluster }}
spec:
  data:
  - secretKey: adminPassword
    remoteRef:
      key: 561166f2-3c06-4c61-9531-422bb0ea3485
  - secretKey: configPassword
    remoteRef:
      key: 223d4d5d-7e70-482d-b923-c80fc9031581
  refreshInterval: 24h0m0s
  secretStoreRef:
    name: cluster
    kind: ClusterSecretStore
  target:
    name: {{ .Values.cluster }}-openldap
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        adminPassword: |-
          {{ "{{ .adminPassword | toString }}" }}
        configPassword: |-
          {{ "{{ .configPassword | toString }}" }}
